from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from jinja2 import Environment, FileSystemLoader, select_autoescape

from ..discover import DiscoveryResult


@dataclass(frozen=True)
class EmitOptions:
    """Options controlling generated sysml2py output."""

    version: str = "0.0.0"
    package_name: str = "sysml2py"


def _template_env() -> Environment:
    templates_dir = Path(__file__).parent / "templates"
    env = Environment(
        loader=FileSystemLoader(str(templates_dir)),
        autoescape=select_autoescape(enabled_extensions=()),
        keep_trailing_newline=True,
    )
    return env


def emit_sysml2py(out_dir: Path, discovery: DiscoveryResult, opts: EmitOptions | None = None) -> Path:
    """
    Write a generated `sysml2py` package to `out_dir/sysml2py/`.

    Returns the path to the generated package root.
    """
    opts = opts or EmitOptions()
    out_dir = out_dir.expanduser().resolve()
    pkg_root = out_dir / opts.package_name
    src_pkg = pkg_root / "src" / opts.package_name

    env = _template_env()

    discovered_keywords = sorted(discovery.statement_prefix_counts.keys())

    # Create directories
    (src_pkg).mkdir(parents=True, exist_ok=True)

    # Render templates
    (pkg_root / "pyproject.toml").write_text(
        env.get_template("pyproject.toml.j2").render(version=opts.version),
        encoding="utf-8",
    )

    (src_pkg / "__init__.py").write_text(
        env.get_template("pkg_init.py.j2").render(discovered_keywords=discovered_keywords),
        encoding="utf-8",
    )

    (src_pkg / "nodes.py").write_text(
        env.get_template("nodes.py.j2").render(discovered_keywords=discovered_keywords),
        encoding="utf-8",
    )

    # Minimal normalize module copied into generated package (so sysml2py is self-contained)
    (src_pkg / "normalize.py").write_text(
        (
            "from __future__ import annotations\n\n"
            "import re\n\n"
            "_ws = re.compile(r\"\\s+\")\n\n"
            "def normalize_text(text: str) -> str:\n"
            "    out_lines: list[str] = []\n"
            "    for raw in text.splitlines():\n"
            "        s = raw.strip()\n"
            "        if not s:\n"
            "            continue\n"
            "        s = _ws.sub(' ', s)\n"
            "        out_lines.append(s)\n"
            "    return '\\n'.join(out_lines) + ('\\n' if out_lines else '')\n"
        ),
        encoding="utf-8",
    )

    # Minimal README for generated package
    (pkg_root / "README.md").write_text(
        (
            "# sysml2py (generated)\n\n"
            "This package was generated by **sysml2py-lab**.\n\n"
            "MVP capabilities:\n"
            "- Generic `Statement`, `Block`, `Document`\n"
            "- `dump()` emits normalized text\n"
        ),
        encoding="utf-8",
    )

    return pkg_root
